/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimateCss: typeof import('./src/components/AnimateCss.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Tooltip: typeof import('./src/components/tooltip/Tooltip.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
